[tool.poetry]
name = "ships-list"
version = "0.1.0"
description = ""
authors = ["Vitaliy Malyshev <vitatomchyk@gmail.com>"]
packages = [
  { include = "ships-list" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
